### ISSUE TITLE
Small adjustments

### ISSUE THREAD

**Issue by sapfeer0k** [Conntac/gitlab-runner-tart#1]
Hi guys,
I've tried the runner it works almost out of the box. Thanks for sharing this amazing piece of software. 

I really want to improve the process of setting the runner and I think it is worth to mention in the `README.md` that a private key needs to be generated before using this executor. 

Second improvement, why would it need to use env variable `CUSTOM_ENV_TART_IMAGE` in base.sh? Would it be better to use built-in gitlab variable `CUSTOM_ENV_CI_JOB_IMAGE`?  Then in the .gitlab-ci.yml configuration `image:` can be specified and the configuration will look more similar to other systems: 
```yaml
build-macos:
  extends: .buildMacOS
  image: ghcr.io/cirruslabs/macos-monterey-xcode:14
  tags: [ macos]
```

If you ok with this approach I could create a pull request.
